# Generated by Django 2.1.9 on 2020-01-03 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='team_type',
            field=models.CharField(choices=[('0', 'دانش آموزی'), ('1', 'دانش جویی')], default='0', max_length=1),
            preserve_default=False,
        ),
    ]
