# Generated by Django 2.1.9 on 2020-01-08 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0002_team_team_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='last_name',
        ),
        migrations.AddField(
            model_name='participant',
            name='name',
            field=models.CharField(default='name', max_length=100),
            preserve_default=False,
        ),
    ]
