# Generated by Django 2.1.9 on 2020-01-11 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0005_auto_20200111_0739'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitionfield',
            name='can_free_register',
            field=models.BooleanField(default=True),
        ),
    ]
