# Generated by Django 2.1.9 on 2020-01-11 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0006_competitionfield_can_free_register'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitionfield',
            name='needs_supervisor',
            field=models.BooleanField(default=True),
        ),
    ]
