# Generated by Django 2.1.9 on 2020-01-11 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0008_auto_20200111_0844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competitionfield',
            name='can_free_register',
        ),
    ]
