# Generated by Django 2.1.9 on 2020-01-14 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0011_auto_20200114_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_type',
            field=models.CharField(choices=[('0', 'شرکت کنندگان در مسابقه'), ('1', 'آزاد دانشجویی'), ('2', 'آزاد سازمانی')], max_length=1),
        ),
    ]
