# Generated by Django 2.1.9 on 2020-01-17 06:58

import competition.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0012_auto_20200114_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='national_card_height_field',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='national_card_width_field',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='student_card_height_field',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='participant',
            name='student_card_width_field',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='national_card_image',
            field=models.ImageField(blank=True, height_field='national_card_width_field', null=True, upload_to=competition.models.national_card_image_upload_location, width_field='national_card_height_field'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='student_card_image',
            field=models.ImageField(blank=True, height_field='student_card_width_field', null=True, upload_to=competition.models.student_card_image_upload_location, width_field='student_card_height_field'),
        ),
    ]
