# Generated by Django 2.1.9 on 2020-01-17 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0016_auto_20200117_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='participant_team',
        ),
    ]
