# Generated by Django 2.1.9 on 2020-01-17 16:29

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('competition', '0017_remove_participant_participant_team'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Advisor',
            new_name='Adviser',
        ),
        migrations.RenameField(
            model_name='competitionfield',
            old_name='needs_advisor',
            new_name='needs_adviser',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='advisor',
            new_name='adviser',
        ),
    ]
