# Generated by Django 2.1.9 on 2020-01-17 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0018_auto_20200117_1629'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='participant',
            new_name='participants',
        ),
    ]
