# Generated by Django 2.1.9 on 2020-01-18 07:42

import competition.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0019_auto_20200117_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='uploaded_file',
            field=models.FileField(blank=True, null=True, upload_to=competition.models.team_uploaded_file_upload_location),
        ),
    ]
