# Generated by Django 2.1.9 on 2020-01-20 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0020_auto_20200118_0742'),
        ('invoice', '0003_auto_20200118_1009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='team',
        ),
        migrations.AddField(
            model_name='invoice',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='competition.Participant'),
        ),
    ]
